# collectionbuilder-gh
# a Jekyll Digital Collection Generator
# designed for GitHub Pages

# Site settings

# title of site appears in banner
title: Research Lab
# tagline appears in banner
tagline: a theme for documenting the work of research teams at the University of Idaho
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Research Lab Template is a template for creating sites that document and disseminate the work of research labs at the University of Idaho"
# keywords appear in meta tags
keywords: "university of idaho, research, labs"
# creator of the digital collection, to appear in meta tags
author: owikle
# creator contact email for meta tags
email: omwikle@uidaho.edu
# collection project date, when did you publish this
collection-date: "2018"

# url is your gh-pages base, following the pattern: username.github.io
url: https://uidaholib.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /researchlab-template
# repository is the github repository's full url
repository: https://github.com/uidaholib/researchlab-template

# Theme Options
# navbar text color
# Choose from "navbar-light" for use with light background colors, or "navbar-dark" for dark background colors
navbar-color: navbar-light
# navbar background color
# Choose from bg-primary, bg-secondary, bg-success, bg-danger, bg-warning, bg-info, bg-light, bg-dark, bg-white
navbar-background: bg-light
# theme with Bootswatch (https://github.com/thomaspark/bootswatch)
# Choose from: cerulean; cosmo; cyborg; darkly; flatly; journal; litera; lumen; lux; materia; minty; pulse; sandstone; simplex; sketchy; slate; solar; spacelab; superhero; united; yeti 
bootswatch: # leave blank or comment out for plain bootstrap

# google services [optional!]
# leave these blank or comment out to NOT include google code
google-tracking-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

# build settings
permalink: pretty

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
